spring:
  datasource:     #数据源配置
    password: 123456   #数据库的密码
    username: root     #数据库的账户
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库的驱动程序类
    url: jdbc:mysql://localhost:3306/subway?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&useSSL=false
  #禁用thmeleaf的缓存
#check out
server:
  port: 8080